<?php

/**
 * Official curriculum module catalogue (examination component breakdown).
 * Key: programme code (uppercase) → NTA level → semester term (1 = Semester I, 2 = Semester II).
 * Weights: CA 40%, SE 60% (per module row sums to 100).
 *
 * Clinical Medicine (CMT): NTA Levels 4–6 (Semesters I & II). Optional per-row `credits` is applied when adding modules.
 * Level 6 Sem I maps Field Report / Proposal / Presentation into WR/AS/CLN columns for this matrix.
 * Medical Laboratory Science (MLT): NTA Levels 4–6 — Sem I & II. Level 5 Sem I General Pathology: SE scaled 60/20 → 45/15 for 100% row total. Level 6 Sem I: research proposal + presentation → `ca_cln`; SE research report → `se_cln` where applicable.
 */
return [
    'defaults' => [
        'ca_weight' => 40,
        'exam_weight' => 60,
    ],

    'programmes' => [
        'CMT' => [
            4 => [
                1 => [
                    [
                        'code' => 'CMT04101',
                        'title' => 'Communication Skills and Customer Care',
                        'ca_wr' => 30, 'ca_as' => 10, 'ca_cln' => null,
                        'se_wr' => 60, 'se_cln' => null,
                        'has_practical' => false,
                        'practical_assessment_type' => null,
                    ],
                    [
                        'code' => 'CMT04102',
                        'title' => 'Human Anatomy',
                        'ca_wr' => 15, 'ca_as' => 5, 'ca_cln' => 20,
                        'se_wr' => 30, 'se_cln' => 30,
                        'has_practical' => true,
                        'practical_assessment_type' => 'practical',
                    ],
                    [
                        'code' => 'CMT04103',
                        'title' => 'Human Physiology',
                        'ca_wr' => 30, 'ca_as' => 10, 'ca_cln' => null,
                        'se_wr' => 60, 'se_cln' => null,
                        'has_practical' => false,
                        'practical_assessment_type' => null,
                    ],
                    [
                        'code' => 'CMT04104',
                        'title' => 'Epidemiology and Biostatistics',
                        'ca_wr' => 15, 'ca_as' => 5, 'ca_cln' => 20,
                        'se_wr' => 30, 'se_cln' => 30,
                        'has_practical' => true,
                        'practical_assessment_type' => 'practical',
                    ],
                    [
                        'code' => 'CMT04105',
                        'title' => 'Computer Applications',
                        'ca_wr' => 15, 'ca_as' => 5, 'ca_cln' => 20,
                        'se_wr' => 25, 'se_cln' => 35,
                        'has_practical' => true,
                        'practical_assessment_type' => 'practical',
                    ],
                    [
                        'code' => 'CMT04106',
                        'title' => 'Medical Ethics and Professionalism',
                        'ca_wr' => 30, 'ca_as' => 10, 'ca_cln' => null,
                        'se_wr' => 60, 'se_cln' => null,
                        'has_practical' => false,
                        'practical_assessment_type' => null,
                    ],
                    [
                        'code' => 'CMT04107',
                        'title' => 'Microbiology, Parasitology and Entomology',
                        'ca_wr' => 15, 'ca_as' => 5, 'ca_cln' => 20,
                        'se_wr' => 30, 'se_cln' => 30,
                        'has_practical' => true,
                        'practical_assessment_type' => 'practical',
                    ],
                ],
                2 => [
                    [
                        'code' => 'CMT04208',
                        'title' => 'Clinical Nutrition',
                        'ca_wr' => 15, 'ca_as' => 5, 'ca_cln' => 20,
                        'se_wr' => 30, 'se_cln' => 30,
                        'has_practical' => true,
                        'practical_assessment_type' => 'practical',
                    ],
                    [
                        'code' => 'CMT04209',
                        'title' => 'Clinical Skills',
                        'ca_wr' => 10, 'ca_as' => 5, 'ca_cln' => 25,
                        'se_wr' => 20, 'se_cln' => 40,
                        'has_practical' => true,
                        'practical_assessment_type' => 'osce',
                    ],
                    [
                        'code' => 'CMT04210',
                        'title' => 'Pathology',
                        'ca_wr' => 30, 'ca_as' => 10, 'ca_cln' => null,
                        'se_wr' => 60, 'se_cln' => null,
                        'has_practical' => false,
                        'practical_assessment_type' => null,
                    ],
                    [
                        'code' => 'CMT04211',
                        'title' => 'Clinical Laboratory',
                        'ca_wr' => 15, 'ca_as' => 5, 'ca_cln' => 20,
                        'se_wr' => 30, 'se_cln' => 30,
                        'has_practical' => true,
                        'practical_assessment_type' => 'practical',
                    ],
                    [
                        'code' => 'CMT04212',
                        'title' => 'Patient Care',
                        'ca_wr' => 15, 'ca_as' => 5, 'ca_cln' => 20,
                        'se_wr' => 30, 'se_cln' => 30,
                        'has_practical' => true,
                        'practical_assessment_type' => 'practical',
                    ],
                ],
            ],
            5 => [
                1 => [
                    [
                        'code' => 'CMT05101',
                        'title' => 'Clinical Pharmacology',
                        'ca_wr' => 30, 'ca_as' => 10, 'ca_cln' => null,
                        'se_wr' => 60, 'se_cln' => null,
                        'has_practical' => false,
                        'practical_assessment_type' => null,
                        'credits' => 10,
                    ],
                    [
                        'code' => 'CMT05102',
                        'title' => 'Internal Medicine I',
                        'ca_wr' => 10, 'ca_as' => 5, 'ca_cln' => 25,
                        'se_wr' => 20, 'se_cln' => 40,
                        'has_practical' => true,
                        'practical_assessment_type' => 'practical',
                        'credits' => 11,
                    ],
                    [
                        'code' => 'CMT05103',
                        'title' => 'Paediatrics and Child Health I',
                        'ca_wr' => 10, 'ca_as' => 5, 'ca_cln' => 25,
                        'se_wr' => 20, 'se_cln' => 40,
                        'has_practical' => true,
                        'practical_assessment_type' => 'practical',
                        'credits' => 12,
                    ],
                    [
                        'code' => 'CMT05104',
                        'title' => 'Obstetrics and Gynaecology I',
                        'ca_wr' => 10, 'ca_as' => 5, 'ca_cln' => 25,
                        'se_wr' => 20, 'se_cln' => 40,
                        'has_practical' => true,
                        'practical_assessment_type' => 'practical',
                        'credits' => 11,
                    ],
                    [
                        'code' => 'CMT05105',
                        'title' => 'Health Promotion',
                        'ca_wr' => 30, 'ca_as' => 10, 'ca_cln' => null,
                        'se_wr' => 60, 'se_cln' => null,
                        'has_practical' => false,
                        'practical_assessment_type' => null,
                        'credits' => 10,
                    ],
                    [
                        'code' => 'CMT05106',
                        'title' => 'Counselling',
                        'ca_wr' => 10, 'ca_as' => 5, 'ca_cln' => 25,
                        'se_wr' => 20, 'se_cln' => 40,
                        'has_practical' => true,
                        'practical_assessment_type' => 'practical',
                        'credits' => 8,
                    ],
                ],
                2 => [
                    [
                        'code' => 'CMT05207',
                        'title' => 'Reproductive and Child Health',
                        'ca_wr' => 10, 'ca_as' => 5, 'ca_cln' => 25,
                        'se_wr' => 20, 'se_cln' => 40,
                        'has_practical' => true,
                        'practical_assessment_type' => 'practical',
                        'credits' => 9,
                    ],
                    [
                        'code' => 'CMT05208',
                        'title' => 'Obstetrics and Gynaecology II',
                        'ca_wr' => 10, 'ca_as' => 5, 'ca_cln' => 25,
                        'se_wr' => 20, 'se_cln' => 40,
                        'has_practical' => true,
                        'practical_assessment_type' => 'practical',
                        'credits' => 12,
                    ],
                    [
                        'code' => 'CMT05209',
                        'title' => 'Surgery',
                        'ca_wr' => 10, 'ca_as' => 5, 'ca_cln' => 25,
                        'se_wr' => 20, 'se_cln' => 40,
                        'has_practical' => true,
                        'practical_assessment_type' => 'practical',
                        'credits' => 12,
                    ],
                    [
                        'code' => 'CMT05210',
                        'title' => 'Internal Medicine II',
                        'ca_wr' => 10, 'ca_as' => 5, 'ca_cln' => 25,
                        'se_wr' => 20, 'se_cln' => 40,
                        'has_practical' => true,
                        'practical_assessment_type' => 'practical',
                        'credits' => 12,
                    ],
                    [
                        'code' => 'CMT05211',
                        'title' => 'Paediatrics and Child Health II',
                        'ca_wr' => 10, 'ca_as' => 5, 'ca_cln' => 25,
                        'se_wr' => 20, 'se_cln' => 40,
                        'has_practical' => true,
                        'practical_assessment_type' => 'practical',
                        'credits' => 13,
                    ],
                ],
            ],
            6 => [
                1 => [
                    [
                        'code' => 'CMT06101',
                        'title' => 'Entrepreneurship and Life Skills',
                        'ca_wr' => 30, 'ca_as' => 10, 'ca_cln' => null,
                        'se_wr' => 60, 'se_cln' => null,
                        'has_practical' => false,
                        'practical_assessment_type' => null,
                        'credits' => 6,
                    ],
                    [
                        'code' => 'CMT06102',
                        'title' => 'Leadership and Management',
                        'ca_wr' => 15, 'ca_as' => 5, 'ca_cln' => 20,
                        'se_wr' => 60, 'se_cln' => null,
                        'has_practical' => true,
                        'practical_assessment_type' => 'practical',
                        'credits' => 12,
                    ],
                    [
                        'code' => 'CMT06103',
                        'title' => 'Operational Research',
                        'ca_wr' => 15, 'ca_as' => 15, 'ca_cln' => 10,
                        'se_wr' => 60, 'se_cln' => null,
                        'has_practical' => false,
                        'practical_assessment_type' => null,
                        'credits' => 14,
                    ],
                    [
                        'code' => 'CMT06104',
                        'title' => 'Basics of Forensic Medicine',
                        'ca_wr' => 30, 'ca_as' => 10, 'ca_cln' => null,
                        'se_wr' => 60, 'se_cln' => null,
                        'has_practical' => false,
                        'practical_assessment_type' => null,
                        'credits' => 8,
                    ],
                    [
                        'code' => 'CMT06105',
                        'title' => 'Surgical Specialties',
                        'ca_wr' => 10, 'ca_as' => 5, 'ca_cln' => 25,
                        'se_wr' => 20, 'se_cln' => 40,
                        'has_practical' => true,
                        'practical_assessment_type' => 'osce',
                        'credits' => 16,
                    ],
                ],
                2 => [
                    [
                        'code' => 'CMT06206',
                        'title' => 'Apprenticeship in Obstetrics and Gynaecology',
                        'ca_wr' => 10, 'ca_as' => 5, 'ca_cln' => 25,
                        'se_wr' => 20, 'se_cln' => 40,
                        'has_practical' => true,
                        'practical_assessment_type' => 'practical',
                        'credits' => 16,
                    ],
                    [
                        'code' => 'CMT06207',
                        'title' => 'Apprenticeship in Surgery',
                        'ca_wr' => 10, 'ca_as' => 5, 'ca_cln' => 25,
                        'se_wr' => 20, 'se_cln' => 40,
                        'has_practical' => true,
                        'practical_assessment_type' => 'practical',
                        'credits' => 16,
                    ],
                    [
                        'code' => 'CMT06208',
                        'title' => 'Apprenticeship in Internal Medicine',
                        'ca_wr' => 10, 'ca_as' => 5, 'ca_cln' => 25,
                        'se_wr' => 20, 'se_cln' => 40,
                        'has_practical' => true,
                        'practical_assessment_type' => 'practical',
                        'credits' => 16,
                    ],
                    [
                        'code' => 'CMT06209',
                        'title' => 'Apprenticeship in Paediatrics and Child Health',
                        'ca_wr' => 10, 'ca_as' => 5, 'ca_cln' => 25,
                        'se_wr' => 20, 'se_cln' => 40,
                        'has_practical' => true,
                        'practical_assessment_type' => 'practical',
                        'credits' => 16,
                    ],
                ],
            ],
        ],
        'MLT' => [
            4 => [
                1 => [
                    [
                        'code' => 'MLT04101',
                        'title' => 'Laboratory Instrumentation',
                        'ca_wr' => 10, 'ca_as' => 5, 'ca_cln' => 25,
                        'se_wr' => 20, 'se_cln' => 40,
                        'has_practical' => true,
                        'practical_assessment_type' => 'ospe',
                        'credits' => 13,
                    ],
                    [
                        'code' => 'MLT04102',
                        'title' => 'General Human Anatomy and Physiology',
                        'ca_wr' => 25, 'ca_as' => 5, 'ca_cln' => 10,
                        'se_wr' => 40, 'se_cln' => 20,
                        'has_practical' => true,
                        'practical_assessment_type' => 'ospe',
                        'credits' => 13,
                    ],
                    [
                        'code' => 'MLT04103',
                        'title' => 'Laboratory Safety and Waste Management',
                        'ca_wr' => 25, 'ca_as' => 5, 'ca_cln' => 10,
                        'se_wr' => 40, 'se_cln' => 20,
                        'has_practical' => true,
                        'practical_assessment_type' => 'ospe',
                        'credits' => 9,
                    ],
                    [
                        'code' => 'MLT04104',
                        'title' => 'Communication and Life Skills',
                        'ca_wr' => 25, 'ca_as' => 5, 'ca_cln' => 10,
                        'se_wr' => 60, 'se_cln' => null,
                        'has_practical' => true,
                        'practical_assessment_type' => 'osce',
                        'credits' => 7,
                    ],
                    [
                        'code' => 'MLT04105',
                        'title' => 'Laboratory Ethics and Code of Conduct',
                        'ca_wr' => 35, 'ca_as' => 5, 'ca_cln' => null,
                        'se_wr' => 60, 'se_cln' => null,
                        'has_practical' => false,
                        'practical_assessment_type' => null,
                        'credits' => 6,
                    ],
                    [
                        'code' => 'MLT04106',
                        'title' => 'Prevention and Control of Communicable & Non-Communicable Diseases',
                        'ca_wr' => 35, 'ca_as' => 5, 'ca_cln' => null,
                        'se_wr' => 60, 'se_cln' => null,
                        'has_practical' => false,
                        'practical_assessment_type' => null,
                        'credits' => 8,
                    ],
                ],
                2 => [
                    [
                        'code' => 'MLT04207',
                        'title' => 'Routine Laboratory Investigations',
                        'ca_wr' => 10, 'ca_as' => 5, 'ca_cln' => 25,
                        'se_wr' => 20, 'se_cln' => 40,
                        'has_practical' => true,
                        'practical_assessment_type' => 'ospe',
                        'credits' => 14,
                    ],
                    [
                        'code' => 'MLT04208',
                        'title' => 'Laboratory Specimen Management',
                        'ca_wr' => 25, 'ca_as' => 5, 'ca_cln' => 10,
                        'se_wr' => 40, 'se_cln' => 20,
                        'has_practical' => true,
                        'practical_assessment_type' => 'ospe',
                        'credits' => 11,
                    ],
                    [
                        'code' => 'MLT04209',
                        'title' => 'Computer Application',
                        'ca_wr' => 10, 'ca_as' => 5, 'ca_cln' => 25,
                        'se_wr' => 20, 'se_cln' => 40,
                        'has_practical' => true,
                        'practical_assessment_type' => 'ospe',
                        'credits' => 13,
                    ],
                    [
                        'code' => 'MLT04210',
                        'title' => 'Systemic Human Anatomy and Physiology',
                        'ca_wr' => 25, 'ca_as' => 5, 'ca_cln' => 10,
                        'se_wr' => 40, 'se_cln' => 20,
                        'has_practical' => true,
                        'practical_assessment_type' => 'ospe',
                        'credits' => 12,
                    ],
                    [
                        'code' => 'MLT04211',
                        'title' => 'Laboratory Reagents and Solutions',
                        'ca_wr' => 10, 'ca_as' => 5, 'ca_cln' => 25,
                        'se_wr' => 20, 'se_cln' => 40,
                        'has_practical' => true,
                        'practical_assessment_type' => 'ospe',
                        'credits' => 14,
                    ],
                ],
            ],
            5 => [
                1 => [
                    [
                        'code' => 'MLT05101',
                        'title' => 'Laboratory Logistic Management',
                        'ca_wr' => 35, 'ca_as' => 5, 'ca_cln' => null,
                        'se_wr' => 60, 'se_cln' => null,
                        'has_practical' => false,
                        'practical_assessment_type' => null,
                        'credits' => 9,
                    ],
                    [
                        'code' => 'MLT05102',
                        'title' => 'Maintenance and Calibration of Laboratory Instruments & Equipment',
                        'ca_wr' => 10, 'ca_as' => 5, 'ca_cln' => 25,
                        'se_wr' => 20, 'se_cln' => 40,
                        'has_practical' => true,
                        'practical_assessment_type' => 'ospe',
                        'credits' => 12,
                    ],
                    [
                        'code' => 'MLT05103',
                        'title' => 'Principles of Entrepreneurship',
                        'ca_wr' => 25, 'ca_as' => 5, 'ca_cln' => 10,
                        'se_wr' => 50, 'se_cln' => 10,
                        'has_practical' => true,
                        'practical_assessment_type' => 'osce',
                        'credits' => 11,
                    ],
                    [
                        'code' => 'MLT05104',
                        'title' => 'Laboratory Quality Assurance',
                        'ca_wr' => 25, 'ca_as' => 5, 'ca_cln' => null,
                        'se_wr' => 60, 'se_cln' => null,
                        'has_practical' => false,
                        'practical_assessment_type' => null,
                        'credits' => 11,
                    ],
                    [
                        'code' => 'MLT05105',
                        'title' => 'Health Records Management',
                        'ca_wr' => 35, 'ca_as' => 5, 'ca_cln' => null,
                        'se_wr' => 60, 'se_cln' => null,
                        'has_practical' => false,
                        'practical_assessment_type' => null,
                        'credits' => 9,
                    ],
                    [
                        'code' => 'MLT05106',
                        'title' => 'General Pathology',
                        'ca_wr' => 25, 'ca_as' => 5, 'ca_cln' => 10,
                        'se_wr' => 45, 'se_cln' => 15,
                        'has_practical' => true,
                        'practical_assessment_type' => 'ospe',
                        'credits' => 8,
                    ],
                ],
                2 => [
                    [
                        'code' => 'MLT05207',
                        'title' => 'Hematology and Blood Transfusion',
                        'ca_wr' => 10, 'ca_as' => 5, 'ca_cln' => 25,
                        'se_wr' => 20, 'se_cln' => 40,
                        'has_practical' => true,
                        'practical_assessment_type' => 'ospe',
                        'credits' => 13,
                    ],
                    [
                        'code' => 'MLT05208',
                        'title' => 'Medical Microbiology and Immunology',
                        'ca_wr' => 10, 'ca_as' => 5, 'ca_cln' => 25,
                        'se_wr' => 20, 'se_cln' => 40,
                        'has_practical' => true,
                        'practical_assessment_type' => 'ospe',
                        'credits' => 14,
                    ],
                    [
                        'code' => 'MLT05209',
                        'title' => 'Clinical Chemistry',
                        'ca_wr' => 10, 'ca_as' => 5, 'ca_cln' => 25,
                        'se_wr' => 20, 'se_cln' => 40,
                        'has_practical' => true,
                        'practical_assessment_type' => 'ospe',
                        'credits' => 12,
                    ],
                    [
                        'code' => 'MLT05210',
                        'title' => 'Medical Parasitology',
                        'ca_wr' => 10, 'ca_as' => 5, 'ca_cln' => 25,
                        'se_wr' => 20, 'se_cln' => 40,
                        'has_practical' => true,
                        'practical_assessment_type' => 'ospe',
                        'credits' => 12,
                    ],
                    [
                        'code' => 'MLT05211',
                        'title' => 'Cytology and Histology',
                        'ca_wr' => 10, 'ca_as' => 5, 'ca_cln' => 25,
                        'se_wr' => 20, 'se_cln' => 40,
                        'has_practical' => true,
                        'practical_assessment_type' => 'ospe',
                        'credits' => 9,
                    ],
                ],
            ],
            6 => [
                1 => [
                    [
                        'code' => 'MLT06101',
                        'title' => 'Laboratory Quality Management',
                        'ca_wr' => 25, 'ca_as' => 5, 'ca_cln' => 10,
                        'se_wr' => 60, 'se_cln' => null,
                        'has_practical' => true,
                        'practical_assessment_type' => 'osce',
                        'credits' => 14,
                    ],
                    [
                        'code' => 'MLT06102',
                        'title' => 'Operational Research',
                        'ca_wr' => 15, 'ca_as' => 5, 'ca_cln' => 20,
                        'se_wr' => 20, 'se_cln' => 40,
                        'has_practical' => true,
                        'practical_assessment_type' => 'practical',
                        'credits' => 12,
                    ],
                    [
                        'code' => 'MLT06103',
                        'title' => 'Principles of Epidemiology and Biostatistics',
                        'ca_wr' => 25, 'ca_as' => 5, 'ca_cln' => 10,
                        'se_wr' => 60, 'se_cln' => null,
                        'has_practical' => true,
                        'practical_assessment_type' => 'osce',
                        'credits' => 12,
                    ],
                    [
                        'code' => 'MLT06104',
                        'title' => 'Leadership and Management',
                        'ca_wr' => 25, 'ca_as' => 5, 'ca_cln' => 10,
                        'se_wr' => 60, 'se_cln' => null,
                        'has_practical' => true,
                        'practical_assessment_type' => 'osce',
                        'credits' => 12,
                    ],
                    [
                        'code' => 'MLT06105',
                        'title' => 'Introduction to Diagnostic Molecular Biology',
                        'ca_wr' => 25, 'ca_as' => 5, 'ca_cln' => 10,
                        'se_wr' => 60, 'se_cln' => null,
                        'has_practical' => true,
                        'practical_assessment_type' => 'osce',
                        'credits' => 10,
                    ],
                ],
                2 => [
                    [
                        'code' => 'MLT06206',
                        'title' => 'Diagnostic Parasitology and Medical Entomology',
                        'ca_wr' => 10, 'ca_as' => 5, 'ca_cln' => 25,
                        'se_wr' => 20, 'se_cln' => 40,
                        'has_practical' => true,
                        'practical_assessment_type' => 'ospe',
                        'credits' => 12,
                    ],
                    [
                        'code' => 'MLT06207',
                        'title' => 'Diagnostic Microbiology and Immunology',
                        'ca_wr' => 10, 'ca_as' => 5, 'ca_cln' => 25,
                        'se_wr' => 20, 'se_cln' => 40,
                        'has_practical' => true,
                        'practical_assessment_type' => 'ospe',
                        'credits' => 14,
                    ],
                    [
                        'code' => 'MLT06208',
                        'title' => 'Diagnostic Clinical Chemistry',
                        'ca_wr' => 10, 'ca_as' => 5, 'ca_cln' => 25,
                        'se_wr' => 20, 'se_cln' => 40,
                        'has_practical' => true,
                        'practical_assessment_type' => 'ospe',
                        'credits' => 10,
                    ],
                    [
                        'code' => 'MLT06209',
                        'title' => 'Diagnostic Histology and Cytology',
                        'ca_wr' => 10, 'ca_as' => 5, 'ca_cln' => 25,
                        'se_wr' => 20, 'se_cln' => 40,
                        'has_practical' => true,
                        'practical_assessment_type' => 'ospe',
                        'credits' => 10,
                    ],
                    [
                        'code' => 'MLT06210',
                        'title' => 'Diagnostic Hematology and Blood Transfusion',
                        'ca_wr' => 10, 'ca_as' => 5, 'ca_cln' => 25,
                        'se_wr' => 20, 'se_cln' => 40,
                        'has_practical' => true,
                        'practical_assessment_type' => 'ospe',
                        'credits' => 14,
                    ],
                ],
            ],
        ],
    ],
];
